-keep class bitter.jnibridge.* { *; }
-keep class com.unity3d.player.* { *; }
-keep interface com.unity3d.player.IUnityPlayerLifecycleEvents { *; }
-keep class org.fmod.* { *; }
-keep class com.google.androidgamesdk.ChoreographerCallback { *; }
-keep class com.google.androidgamesdk.SwappyDisplayManager { *; }
-keep class com.unity3d.nativecommunication.* { *; }
-keep class com.renderheads.AVPro.Video.* { *; }
-keep class com.unity3d.plugin.* { *; }
-ignorewarnings